name: Hello World Test

on:
  workflow_dispatch:   # allows manual trigger
  push:                # runs on every push

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - name: Say hello
        run: echo "👋 Hello from GitHub Actions!"
