name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Print system info
        run: |
          echo "✅ Running on my self-hosted runner"
          uname -a
          lsb_release -a || true
